name: Install Dependencies
description: Sets up Bun, then installs all dependencies

inputs:
  anchor:
    description: Install Anchor if `true`. Defaults to `false`.
    required: false
  cargo-cache-key:
    description: The key to cache cargo dependencies. Skips cargo caching if not provided.
    required: false
  cargo-cache-fallback-key:
    description: The fallback key to use when caching cargo dependencies. Default to not using a fallback key.
    required: false
  cargo-cache-local-key:
    description: The key to cache local cargo dependencies. Skips local cargo caching if not provided.
    required: false
  clippy:
    description: Install Clippy if `true`. Defaults to `false`.
    required: false
  rustfmt:
    description: Install Rustfmt if `true`. Defaults to `false`.
    required: false
  solana:
    description: Install Solana if `true`. Defaults to `false`.
    required: false

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version: lts/krypton

    - name: Install bun
      uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2
      with:
        bun-version-file: '.bun-version'

    - name: Install dependencies
      shell: bash
      run: bun install

    # TODO: This check can go when this issue is fixed https://github.com/oven-sh/bun/issues/24223
    - name: Check for dirty git repo
      shell: bash
      run: git diff --quiet --ignore-submodules HEAD

    - name: Set Environment Variables
      shell: bash
      run: bun zx ./scripts/ci/set-env.mjs

    - name: Install Rustfmt
      if: ${{ inputs.rustfmt == 'true' }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.TOOLCHAIN_FORMAT }}
        components: rustfmt

    - name: Install Clippy
      if: ${{ inputs.clippy == 'true' }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.TOOLCHAIN_LINT }}
        components: clippy

    - name: Install Solana
      if: ${{ inputs.solana == 'true' }}
      uses: solana-program/actions/install-solana@v1
      with:
        version: ${{ env.SOLANA_VERSION }}
        cache: true

    - name: Generate Solana Keypair
      if: ${{ inputs.solana == 'true' }}
      shell: bash
      run: solana-keygen new --no-bip39-passphrase

    - name: Install Linux dependencies
      if: runner.os == 'Linux' && inputs.anchor == 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev

    - name: Install Anchor
      if: ${{ inputs.anchor == 'true' }}
      uses: metaplex-foundation/actions/install-anchor-cli@v1
      with:
        version: ${{ env.ANCHOR_VERSION }}
        cache: true

    - name: Cache Cargo Dependencies
      if: ${{ inputs.cargo-cache-key && !inputs.cargo-cache-fallback-key }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ inputs.cargo-cache-key }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-${{ inputs.cargo-cache-key }}

    - name: Cache Cargo Dependencies With Fallback
      if: ${{ inputs.cargo-cache-key && inputs.cargo-cache-fallback-key }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ inputs.cargo-cache-key }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cargo-cache-key }}
          ${{ runner.os }}-${{ inputs.cargo-cache-fallback-key }}-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-${{ inputs.cargo-cache-fallback-key }}

    - name: Cache Local Cargo Dependencies
      if: ${{ inputs.cargo-cache-local-key }}
      uses: actions/cache@v4
      with:
        path: |
          .cargo/bin/
          .cargo/registry/index/
          .cargo/registry/cache/
          .cargo/git/db/
        key: ${{ runner.os }}-${{ inputs.cargo-cache-local-key }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-${{ inputs.cargo-cache-local-key }}
